### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by p-baum** [cssninjaStudio/fresh#18]
```
[14:37:42] Using gulpfile /xxx/fresh/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

when I run `gulp dev`

```
$ node -v
v14.8.0
$ npm -v
6.14.7
$ gulp -v
[14:33:43] CLI version 3.9.1
[14:33:43] Local version 4.0.2
```

Arch linux

**Comment by cssninjaStudio** [comment]
Hi,

your node js version seems to be too high. Please downgrade to 10.15.3 LTS.

It should solve your issue.

**Comment by p-baum** [comment]
Thankyou for the response.

Still no go...
```
$ npm instal
...
added 1353 packages from 962 contributors and audited 1423 packages in 16.002s
found 665 vulnerabilities (647 low, 8 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ gulp dev
[11:23:51] Using gulpfile /xxx/fresh/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^
TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
$ node -v
v10.15.3
$ npm -v
6.4.1
[x@xdesktop fresh]$ gulp -v
[11:24:46] CLI version 3.9.1
[11:24:46] Local version 4.0.2
```

**Comment by cssninjaStudio** [comment]
Your CLI version is still on v3 for gulp. Could you upgrade to 4.x?
